on: [push]

name: Hello Snake!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: 'npm install, build, and test'
      run: |
        npm install
               
    # deploy web app using Azure credentials
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./test.zip ./

    - shell: bash
      run: |
          curl --data-binary @test.zip -u ${{ env.AZURE_WEBAPP_NAME }}:${{ env.AZURE_WEBAPP_PUBLISHING_PWD}} https://${{ env.AZURE_WEBAPP_NAME }}.scm.${{ env.K8SE_CLUSTER_NAME }}.k4apps-example.io --resolve ${{ env.AZURE_WEBAPP_NAME }}.scm.${{ env.K8SE_CLUSTER_NAME }}.k4apps-example.io:443:${{ env.K8SE_CLUSTER_IP }} -v --insecure 
